---
title: "Very first to at webr"
format: html
engine: knitr
filters:
  - webr
webr:
  packages: ['tidyverse']
---

```{webr-r}
# set a random seed and generate data
set.seed(123)
x <- rnorm(100)

# calculate mean
mean(x)
```

```{}
webr::install("dplyr")
```

```{webr}
# do some dplyr stuff
```

more stuff

```{webr}
# do some dplyr stuff
```

## Exercise

Make a scatter plot with `hp` on the x axis and `wt` on the y axis. Label the x axis "Horse Power" and the y axis “Weight”.
Make one subplot for each value in `gear`.

```{webr-r}
# Add you code here
```

Your result should look like the plot below
:::

::: {.callout-tip collapse="true"}
## Expected Result

```{r}
#| echo: false
library(ggplot2)
ggplot(mtcars, aes(x = hp, y = wt)) +
  geom_point() +
  labs(x = "Horse Power", y = "Weight") +
  facet_wrap(~gear)
```
:::

::: {.callout-tip collapse="true"}
## Solution Code

```{r}
#| echo: true
#| eval: false
library(ggplot2)
ggplot(mtcars, aes(x = hp, y = wt)) +
  geom_point() +
  labs(x = "Horse Power", y = "Weight") +
  facet_wrap(~gear)
```
:::